apiVersion: apps/v1
kind: Deployment
metadata:
name: hello
labels:
  app: hello
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: hello
      image: giaple/demo:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 6000
        name: hello

---
apiVersion: v1
kind: Service
metadata:
name: hello
labels:
  app: hello
spec:
ports:
  - port: 6000
    targetPort: 6000
selector:
  app: hello
  tier: hello
type: LoadBalancer